environments:
	sed 's/$${environment}/test/' template.css > testing.css
	sed 's/$${environment}/staging/' template.css > staging.css
	sed 's/$${environment}/prod/' template.css > production.css

# Comment to allow rebuild
